---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: linkerd
    server: 'https://kubernetes.default.svc'
  source:
    path: overlays/dev
    repoURL: >-
      https://github.com/Tomelin/linkerd-argocd.git
    targetRevision: main
  project: linkerd
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
