---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: linkerd
  namespace: argocd
spec:
  description: Linkerd Service Mesh
  destinations:
  - name: '*'
    namespace: '*'
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/Tomelin/linkerd-argocd.git
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'